chore: linting with shfmt

diff --git a/git/.config/git/templates/hooks/pre-commit b/git/.config/git/templates/hooks/pre-commit
--- a/git/.config/git/templates/hooks/pre-commit
+++ b/git/.config/git/templates/hooks/pre-commit
@@ -2,19 +2,18 @@
 files_commit=$(git diff --cached --name-only --diff-filter=ACM)
 
 for file in $files_commit; do
-    if [[ $file =~ pm|pl$ ]]
-    then
-        if ! perl -c "$file"; then
-            echo "Perl syntax check failed for file: $file"
-            exit 1
-        fi
-        if [[ "$(perltidy -b -bext='/' $file)" -gt 0 ]]; then
-         echo >&2 "There was an error when running perltidy on $file; please see the error file for more info"
-            exit 1
-       fi
-        if ! [[ "$(perlcritic $file)" =~ 'source OK'  ]]; then
-            echo >&2 "There was some error when running perlcritic on $file: $(perlcritic $file)"
-            exit 1
-        fi
-    fi
+	if [[ $file =~ pm|pl$ ]]; then
+		if ! perl -c "$file"; then
+			echo "Perl syntax check failed for file: $file"
+			exit 1
+		fi
+		if [[ "$(perltidy -b -bext='/' "$file")" -gt 0 ]]; then
+			echo >&2 "There was an error when running perltidy on $file; please see the error file for more info"
+			exit 1
+		fi
+		if ! [[ "$(perlcritic "$file")" =~ 'source OK' ]]; then
+			echo >&2 "There was some error when running perlcritic on $file: $(perlcritic "$file")"
+			exit 1
+		fi
+	fi
 done
